### ISSUE TITLE
Finding offsets........Error: Failed to get a module

### ISSUE THREAD

**Issue by Cra4ck** [h1ru5/heck_exe#1]
![image](https://user-images.githubusercontent.com/37532063/87901384-7629c280-ca89-11ea-9161-00c980ec0d55.png)

**Comment by soyware** [comment]
client_panorama.dll was changed to client.dll . Would be neat if you opened a pull request with it and signatures updated.

**Comment by Cra4ck** [comment]
> client_panorama.dll was changed to client.dll . Would be neat if you would make pull request with it and signatures updated.

Thanks, works fine
