### ISSUE TITLE
Random.hpp + Sig

### ISSUE THREAD

**Issue by AlexanderQueen** [h1ru5/heck_exe#6]
For what response Random.HPP? Also, where to find hashed signatures like yours?

P.S Crashes on start, no debug info. Used .exe from release section. W7/x86

**Comment by soyware** [comment]
latest build works fine

**Comment by AlexanderQueen** [comment]
"For what response Random.HPP? Also, where to find hashed signatures like yours?" I mean not encryped, in public for sure.
What abotut this question?

P.S I will try to compile then will come with an feedback.
(without libcurl also crashes),build in W7/x86.

**Comment by soyware** [comment]
Random.hpp contains functions Valve uses to generate random spread, we use it for hitchance. "\x" used in signatures, is an escape sequence used to generate character by it's code

**Comment by AlexanderQueen** [comment]
What version of openssl you used? Because it cancer to get a normal one to compile.Everytime errors...

P.S i will come back with an review again if it works or not.

**Comment by soyware** [comment]
bro it cant crash because of curl just debug the fucking program

**Comment by AlexanderQueen** [comment]
> bro it cant crash because of curl just debug the fucking program

I can't debug it because everytime i debug i get error: LINK : fatal error LNK1104: can't open file "libcurld.lib". And this shit happens only in debug, in release it compiles with a dozens of warnings but compiles, put the libcurl.dll in same path as "heck.exe". It opens and a few seconds crash. 
Set path, added additional dependencies, #pragma commented it, nothing.

**Comment by AlexanderQueen** [comment]
It 100% from CURL and Memory.hpp.

**Comment by AlexanderQueen** [comment]
I come back. Now it compiled in debug 100% with curl libraries. Put the .dll in same path as heck.exe and it also crashed. Give a look to code and see why this happens. Or it curl or it signatures 100%.Remove curl from source and let me test again.

P.S And what library you use  from that?

curl[ssl]:x86-windows                  Default SSL backend
curl[sspi]:x86-windows                 SSPI support
curl[winssl]:x86-windows               SSL support (Secure Channel / "WinSSL")
