### ISSUE TITLE
Heck Debugged

### ISSUE THREAD

**Issue by AlexanderQueen** [h1ru5/heck_exe#7]
Give a look:
![heck debugged](https://user-images.githubusercontent.com/55955916/98447482-cbb7d700-212d-11eb-9197-6358b187ae3a.png)

I debugged it till end, so i get this. Build in [debugged mode]

Build in [Release]
![Invalid Octal Digit](https://user-images.githubusercontent.com/55955916/98449638-c2cf0180-213d-11eb-8c19-0ff1f05fa135.png)

**Comment by AlexanderQueen** [comment]
Build in [Release]
![Invalid Octal Digit](https://user-images.githubusercontent.com/55955916/98449638-c2cf0180-213d-11eb-8c19-0ff1f05fa135.png)

**Comment by soyware** [comment]
You processor doesnt support AVX, select SSE2 in Enable Enchanced Instruction Set in Project properties
